name: Trigger auto deployment for shl-recommender

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/shl-recommender-AutoDeployTrigger-aad00edb-6756-47c2-a3eb-591d60867f2e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SHLRECOMMENDER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SHLRECOMMENDER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SHLRECOMMENDER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUsername: ${{ secrets.SHLRECOMMENDER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHLRECOMMENDER_REGISTRY_PASSWORD }}
          containerAppName: shl-recommender
          resourceGroup: shl-assessment
          imageToBuild: shl-recommender:${{ github.sha }}



